Remove nominations page
coopsoc/website pull request #56
Opened 2024-01-14 07:22 UTC by KKSurendran06

Changes - 
* I Removed the "Nominations" link from the navigation header.
* I  Implemented a conditional rendering approach to display a message indicating that nominations are closed and encourage users to return next year.

Highlights - 
* I Introduced a showNominations variable to control the visibility of the "Nominations" page.
* I Modified the Nominations component to conditionally render a message indicating that nominations are currently closed.

2024-01-16 11:08 UTC, scorpiontornado requested changes
Generally good, but should address my feedback before merging.

2024-01-16 11:08 UTC, scorpiontornado commented on components/Navigation.jsx
> -                </NavItem>
Good

2024-01-16 11:08 UTC, scorpiontornado commented on pages/nominations.jsx
>      <>
Currently lacking a title, would be nice to fix in this PR

```suggestion
    <>
      <Head>
        <title>Nominations | UNSW Co-op Society</title>
      </Head>
```

2024-01-16 11:08 UTC, scorpiontornado commented on pages/nominations.jsx
> +    );
Nice idea, but needs a few tweaks to be consistent with the rest of the website. Would appreciate some input from @lhvy

Changes (NOTE - UNTESTED. MUST BE RUN LOCALLY BEFORE MERGING):
- Added title, same as other pages (realised we currently don't have one)
- Changed formatting to be consistent with other pages (e.g. [events](https://github.com/coopsoc/coopsoc.com.au/blob/62925b7820bb9c7ac71f912b74228b565685a25d/pages/events.jsx#L33) and [publications)](https://github.com/coopsoc/coopsoc.com.au/blob/62925b7820bb9c7ac71f912b74228b565685a25d/pages/publications.jsx#L30C1-L30C1) (aside: why did Hanyuan have multiple containers, rather than one big container with several rows..?)
- Changed language to refer to voting being closed, rather than nominations; added more fluff using chatgpt hehe

```suggestion
    return (
      <>
        <Head>
          <title>Nominations | UNSW Co-op Society</title>
        </Head>
  
        <section className="section section-lg">
          <Row className="justify-content-center text-center ">
            <Col lg="8">
              <h1 className="animate__animated animate__zoomIn animate__fast">VOTING CLOSED</h1>
            </Col>
          </Row>

          <Container className="py-lg-md d-flex">
            <Row className="justify-content-center text-center">
              <Col lg="10">
                <p className="lead text-muted">
                  Thank you for participating! The voting process for the new executive team has concluded. Come back at the end of this year for the next round of nominations!
                </p>
              </Col>
            </Row>
          </Container>
        </section>
      </>
    );
```

2024-01-16 14:49 UTC, KKSurendran06 commented on pages/nominations.jsx
> +    );
Will do the changes but, I see you have used head tag but, head is not imported in the code. I will do a Pr fixing that

2024-01-16 14:50 UTC, KKSurendran06 commented
Will do the changes but, I see you have used head tag but, head is not imported in the code. I will do a Pr fixing that

2024-01-16 14:57 UTC, KKSurendran06 commented
Have implemented your changes and also I have added an commit to import Head in the coede

2024-01-16 18:15 UTC, scorpiontornado commented
Thanks, nice catch

2024-01-16 18:37 UTC, scorpiontornado approved these changes
Looks good to me, I'll wait for @lhvy before merging though
![image](https://github.com/coopsoc/coopsoc.com.au/assets/40455550/42741cca-27b2-49f8-9b4e-93b98cf1a6f3)

2024-01-17 03:31 UTC, scorpiontornado commented
Was considering utilising inline conditional rendering (e.g. ternary) to avoid repeated code like the head/title, and the fluff around the h1, but it ended up being too convoluted. I think how it is currently is the best solution, apart from a complete rewrite abstracting sections into different components like NomineeSection and NominationInfo.

2024-01-17 03:34 UTC, scorpiontornado approved these changes
Meant to request @lhvy rather than re-request review from myself, oops

2024-01-17 04:10 UTC, lhvy approved these changes
Looks good to me. Remember to add `Resolves #xx` to your PR description so the associated issue will close automatically.

2024-01-17 04:21 UTC, merged