Update team 2024
coopsoc/website pull request #69
Opened 2024-05-12 11:40 UTC by timesth

Changed Co-op Soc team for 2024

2024-05-12 19:20 UTC, scorpiontornado requested changes
Looks good, just minor formatting issues

2024-05-12 19:20 UTC, scorpiontornado commented on data/TeamData.js
> +            //Get Tony's Pic
Don't need this comment

2024-05-12 19:20 UTC, scorpiontornado commented on data/TeamData.js
> +            // },
Don't think this should be commented out

2024-05-12 19:20 UTC, scorpiontornado commented on data/TeamData.js
> +        members: ["Stella Lin", "James Liao", "Aiden Ahmad", "Rashid Abuzarov"],
Formatting - one per line. Make sure to set up eslint / formatter, ask @lhvy for help if needed

2024-05-12 19:20 UTC, scorpiontornado commented on data/TeamData.js
> +        members: ["Jamie Hilliam", "Jack Preller", "Declan Gormley"],
Same - formatting

2024-05-12 19:20 UTC, scorpiontornado commented on data/TeamData.js
> +            // },
Nvm she's now copres instead. Should delete rather than uncommenting out

2024-05-13 09:04 UTC, timesth commented
Fixed code based on feedback

2024-05-13 09:10 UTC, scorpiontornado commented
Also be mindful of commit naming conventions, eg starting with a capital

2024-05-13 09:11 UTC, timesth commented
Will keep it lowercase in future commits. Thanks Nick.

2024-05-22 17:54 UTC, scorpiontornado requested changes, later dismissed
Still think there are some formatting issues, have you set up the linter/formatter? If not, we can probably help you in the next meeting.

2024-05-22 17:54 UTC, scorpiontornado commented on data/TeamData.js
> +        sectionName: "First Year Representatives",
```suggestion
        sectionName: "First Year Representative",
```
Probably should update now that Mariam's changed roles

2024-05-22 17:54 UTC, scorpiontornado commented on data/TeamData.js
> +        members: ["Jamie Hilliam", "Jack Preller", "Declan Gormley"],
Formatting

2024-05-22 17:54 UTC, scorpiontornado commented on data/TeamData.js
> +        members: ["Jamie Hilliam", "Jack Preller", "Declan Gormley"],
This should really be picked up by eslint - should add to the CI/CD pipeline if not there already. Also, should just happen automatically with a formatter

2024-05-22 17:54 UTC, scorpiontornado commented on data/TeamData.js
> +        members: ["Jamie Hilliam", "Jack Preller", "Declan Gormley"],
Same for HR

2024-05-22 17:54 UTC, scorpiontornado commented on data/TeamData.js
> +        members: ["Stella Lin", "James Liao", "Aiden Ahmad", "Rashid Abuzarov"],
Don't think this was done, I meant something like:
```js
members: [
  "Stella Lin",
  "James Liao",
  "Aiden Ahmad",
  "Rashid Abuzarov",
]
```

Should be automated by the linter/formatter. Let me know if the formatter chose to do it this way, but looks more like you just not setting it up yet.

2024-05-22 17:57 UTC, scorpiontornado commented
> Will keep it lowercase in future commits. Thanks Nick.

Actually, it should be sentence case like you had in a few of them, like "Update team data after 2024 EGM" and "Change Rashid's surname" - first letter should be capitalised. Good use of imperative verbs by the way.

2024-06-02 08:35 UTC, timesth commented
Hey Nick, ive made the formatting changes, not too sure how to set up eslint yet, hopefully we can discuss on Wednesday.

2024-06-03 05:03 UTC, lhvy commented
Checked on my machine, formatting is fine. Good to merge.

2024-06-03 05:04 UTC, lhvy approved these changes, later dismissed

2024-06-03 05:05 UTC, lhvy approved these changes

2024-06-03 05:07 UTC, merged